<?php

return [
    'knowledge_base_path' => env('GYMMI_KNOWLEDGE_BASE_PATH') ?: resource_path('data/gymmi/knowledge-base.json'),
    'knowledge_overrides_path' => env('GYMMI_KNOWLEDGE_OVERRIDES_PATH') ?: resource_path('data/gymmi/knowledge-overrides.json'),
    'knowledge_source_path' => env('GYMMI_KNOWLEDGE_SOURCE_PATH') ?: base_path('platinumgym-figma/docs/source-data/data_AI_Chatbot.xlsx'),
    'normalizer' => [
        'phrases' => [
            'muay thai' => 'muaythai',
            'muay tay' => 'muaythai',
            'muay tai' => 'muaythai',
            'muay thay' => 'muaythai',
            'pound fit' => 'poundfit',
            'personal trainer' => 'personal trainer',
            'google map' => 'google maps',
            'google maps' => 'google maps',
            'terima kasih' => 'terima kasih',
            'thank you' => 'terima kasih',
            'makasih banyak' => 'terima kasih',
            'selamat pagi' => 'selamat pagi',
            'selamat siang' => 'selamat siang',
            'selamat sore' => 'selamat sore',
            'selamat malam' => 'selamat malam',
        ],
        'words' => [
            'ad' => 'ada',
            'adlh' => 'adalah',
            'aja' => 'saja',
            'aj' => 'saja',
            'ak' => 'saya',
            'akuwh' => 'aku',
            'aq' => 'saya',
            'ato' => 'atau',
            'bangettt' => 'banget',
            'bangedh' => 'banget',
            'bgt' => 'banget',
            'bgtt' => 'banget',
            'bgttt' => 'banget',
            'brp' => 'berapa',
            'book' => 'booking',
            'boking' => 'booking',
            'buking' => 'booking',
            'byr' => 'bayar',
            'class' => 'kelas',
            'dah' => 'sudah',
            'dftr' => 'daftar',
            'dmn' => 'dimana',
            'dr' => 'dari',
            'dri' => 'dari',
            'engga' => 'tidak',
            'enggak' => 'tidak',
            'fitnes' => 'gym',
            'fitness' => 'gym',
            'ga' => 'tidak',
            'gak' => 'tidak',
            'gim' => 'gym',
            'gimana' => 'bagaimana',
            'gimanaa' => 'bagaimana',
            'gimanaaa' => 'bagaimana',
            'gimna' => 'bagaimana',
            'gimn' => 'bagaimana',
            'gmn' => 'bagaimana',
            'gymm' => 'gym',
            'haii' => 'hai',
            'haiii' => 'hai',
            'hay' => 'hai',
            'hayy' => 'hai',
            'hayyy' => 'hai',
            'hii' => 'hai',
            'hiii' => 'hai',
            'hi' => 'hai',
            'hrg' => 'harga',
            'hrgny' => 'harganya',
            'jadual' => 'jadwal',
            'jdl' => 'jadwal',
            'jdwl' => 'jadwal',
            'jim' => 'gym',
            'klas' => 'kelas',
            'kls' => 'kelas',
            'km' => 'kamu',
            'kmu' => 'kamu',
            'lo' => 'kamu',
            'loe' => 'kamu',
            'lok' => 'lokasi',
            'maaciw' => 'terima kasih',
            'maacih' => 'terima kasih',
            'makasih' => 'terima kasih',
            'mbr' => 'member',
            'membershipnya' => 'membership',
            'mksh' => 'terima kasih',
            'muaytai' => 'muaythai',
            'muaytay' => 'muaythai',
            'muaythay' => 'muaythai',
            'nda' => 'tidak',
            'ndak' => 'tidak',
            'ngga' => 'tidak',
            'nggak' => 'tidak',
            'nope' => 'tidak',
            'pdhl' => 'padahal',
            'pls' => 'tolong',
            'plis' => 'tolong',
            'qrisnya' => 'qris',
            'regis' => 'daftar',
            'reserv' => 'booking',
            'schedule' => 'jadwal',
            'skrg' => 'sekarang',
            'sm' => 'sama',
            'sma' => 'sama',
            'tengkyu' => 'terima kasih',
            'thanks' => 'terima kasih',
            'thx' => 'terima kasih',
            'tks' => 'terima kasih',
            'trf' => 'transfer',
            'trims' => 'terima kasih',
            'trs' => 'terus',
            'ttg' => 'tentang',
            'tq' => 'terima kasih',
            'treiner' => 'trainer',
            'tdk' => 'tidak',
            'utk' => 'untuk',
            'wa' => 'whatsapp',
            'ya' => 'iya',
            'yaa' => 'iya',
            'yap' => 'iya',
            'yg' => 'yang',
        ],
        'canonical_terms' => [
            'admin',
            'akun',
            'alamat',
            'aerobic',
            'bagaimana',
            'bayar',
            'berapa',
            'bmi',
            'booking',
            'coach',
            'daftar',
            'dari',
            'gym',
            'hai',
            'halo',
            'harga',
            'instagram',
            'invoice',
            'iya',
            'jadwal',
            'kelas',
            'lokasi',
            'member',
            'membership',
            'muaythai',
            'paket',
            'personal',
            'poundfit',
            'produk',
            'profil',
            'promo',
            'qr',
            'qris',
            'sesi',
            'stok',
            'terima',
            'tidak',
            'trainer',
            'transaksi',
            'untuk',
            'whatsapp',
            'zumba',
        ],
    ],
];
